PROC-292 - Implementar SDK HealthCheck WCF
AndrePostiga/AspNetStandard.Diagnostics.HealthChecks pull request #4
Opened 2021-08-02 14:53 UTC by HelenMinin

# Descrição
 
### Tarefa [PROC-292](https://mundipagg.atlassian.net/browse/PROC-292)

Criar SDK com endpoint para HealthCheck para aplicações WCF. A SDK precisa oferecer:
* Rota pra HealthCheck
* Verificação de conectividade com SQL Server
* Ping para outras APIs internas

### Tipos de alterações

- [ ] Correção de bug 
- [x] Nova feature 
- [ ] Alteração ou remoção de funcionalidade existente
- [ ] Atualização de documentação

## Testes
Retorno da requisição 
![image](https://user-images.githubusercontent.com/42481661/127880933-940fd61a-3532-47e8-b968-376430d3b0ea.png)

## Checklist

- [x] Associei corretamente a Tarefa do Board ao Pull Request.
- [x] Meu código segue as diretrizes desse projeto.
- [x] Eu revisei meu próprio código.
- [ ] Eu comentei meu código em áreas particulares de difícil compreensão.
- [x] Eu atualizei a documentação de acordo com as mudanças realizadas.
- [x] Meu código não gerou novos warnings.
- [x] Eu adicionei testes que provam que minha correção é efetiva ou que a nova feature funciona.
- [x] Testes novos e existentes passam localmente com minhas alterações. 
- [ ] Testes novos e existentes passam em staging com minhas alterações. 
- [ ] Qualquer dependência dessa alteração já foi realizada (deploy, configuração em todos os ambientes, etc).

2021-08-02 15:05 UTC, ericksavassa commented on src/AspNetStandard.Diagnostics.HealthChecks.Tests/AspNetStandard.Diagnostics.HealthChecks.Tests.csproj
> -    <TargetFramework>net5.0</TargetFramework>
Talvez seja bom usar, no projeto de Tests, os mesmos targets que a aplicação já usa.
`		<TargetFrameworks>netstandard2.0;net461;net472</TargetFrameworks>`

2021-08-02 15:05 UTC, ericksavassa commented on src/AspNetStandard.Diagnostics.HealthChecks.Tests/AspNetStandard.Diagnostics.HealthChecks.Tests.csproj
> +    <TargetFramework>net461</TargetFramework>
Talvez seja bom usar, no projeto de Tests, os mesmos targets que a aplicação já usa.
`<TargetFrameworks>netstandard2.0;net461;net472</TargetFrameworks>`

2021-08-02 17:08 UTC, vpecanha requested changes
Não encontrei método para fechar telnet a partir do DNS conforme descrição.
Onde estaria?

2021-08-02 17:08 UTC, vpecanha commented on src/AspNetStandard.Diagnostics.HealthChecks.Tests/AspNetStandard.Diagnostics.HealthChecks.Tests.csproj
> +    <TargetFramework>net461</TargetFramework>
Concordo com o @ericksavassa. Temos que garantir a retrocompatibilidade da SDK.

2021-08-02 17:08 UTC, vpecanha commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHeathCheckRouteExtension.cs
> +        public static WcfHealthCheckBuilder AddWcfHealthCheck()
Deixaria explícito desta maneira:

```suggestion
        public static WcfHealthCheckBuilder AddWcfHealthCheckEndpoint()
```

2021-08-02 17:08 UTC, vpecanha commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/README.md
> +                .AddCheck("MyApi", new WcfHealthCheck()) // Faz o setup para o HealthCheck WCF
Porque existe este check se o endpoint já foi criado acima?

2021-08-02 17:08 UTC, vpecanha commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHealthCheckBuilder.cs
> +    public class WcfHealthCheckBuilder
Esta classe deveria ser selada

2021-08-02 17:08 UTC, vpecanha commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHealthCheckBuilder.cs
> +        public WcfHealthCheckBuilder AddCheck(string name, IHealthCheck healthCheck)
Acho que isso daqui é uma decisão que o @AndrePostiga deverá participar:

Pelo que entendi as classes que herdam _IHealthCheck_ não são públicas para utilização na SDK então não seria possível utilizarmos.
Com isso o ideal aqui seria criar um "AddSqlServerCheck(xxx)" com os parâmetros necessários para sua utilização e dentro dele instanciar//injetar o _SqlServerHealthCheck_.

Esse trabalho todo cai por terra se decidirmos expor as implementações de IHealthCheck e funcionaria da mesma maneira conforme implementado agora. Teríamos que verificar apenas se as implementações não estão expondo algo desnecessário.

2021-08-02 17:08 UTC, vpecanha commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHealthCheckBuilder.cs
> +        public WcfHealthCheckBuilder AddCheck(string name, IHealthCheck healthCheck)
Ainda assim, mesmo a gente tome a decisão de expor as implementações de IHealthCheck eu criaria métodos específicos para checks. 

Exemplo:
- AddSqlServerCheck(params[] any, SqlServerHealthCheck)
- AddTelnetCheck(params[] any, TelnetHealthCheck)

etc...

2021-08-02 21:49 UTC, HelenMinin commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/README.md
> +                .AddCheck("MyApi", new WcfHealthCheck()) // Faz o setup para o HealthCheck WCF
Na verdade esse check te da mais detalhes, não precisa dele, necessariamente.
Sem ele ficaria assim o retorno 
![image](https://user-images.githubusercontent.com/42481661/127928244-1ca29f69-10e2-4ea0-a362-27cc1467693d.png)

2021-08-02 21:53 UTC, HelenMinin commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHealthCheckBuilder.cs
> +    public class WcfHealthCheckBuilder
Feito.

2021-08-02 21:54 UTC, HelenMinin commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHealthCheckBuilder.cs
> +        public WcfHealthCheckBuilder AddCheck(string name, IHealthCheck healthCheck)
Vou marcar uma call o @AndrePostiga.

2021-08-03 14:11 UTC, AndrePostiga commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHeathCheckRouteExtension.cs
> +    public static class WcfHeathCheckRouteExtension
Namespace faltando um L "WcfHealthCheckRouteExtension"

2021-08-03 14:16 UTC, AndrePostiga commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHeathCheckRouteExtension.cs
> +        public static WcfHealthCheckBuilder AddWcfHealthCheck()
-> Acho que não tem problema ser Create, mas no padrão do pra web-api está com Add

2021-08-03 14:19 UTC, AndrePostiga commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHeathCheckRouteExtension.cs
> +            RouteTable.Routes.Add(new ServiceRoute("health/", new WebServiceHostFactory(),
-> Acho que seria interessante receber a string que vai compor a URL do endpoint via parâmetro, pode até colocar health como um parâmetro default

Em outra aplicação optamos por colocar "core/v1/health" no momento da configuração, a lib não tem como saber se existe algum path antes de configurar o endpoint.

Se tivéssemos configurado direto sem passar o core/v1 ficaria : domínio.com.br/health?apikey=***** impossibilitando identificar de qual recurso era aquele healthCheck

2021-08-03 14:29 UTC, AndrePostiga commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHealthCheckConfiguration.cs
> +        public static IDictionary<string, IHealthCheck> HealthChecksDependencies { get; }
Tomar cuidado com o gerenciamento de instâncias das classes que implementam IHealthCheck

Na lib original temos um wrapper chamado Registration, que ele registra tanto uma instância que implementa IHealthCheck, quanto um tipo que vai ser resolvido posteriormente.

Na implementação é possível passar tanto como:
.AddCheck("mongodb", new MongoDbHealthCheck("connstring");

ou como tipo
.AddCheck<MongoDbHealthCheck>();

Que será resolvido baseado no gerenciador de dependências da aplicação, que no web_api é comum utilizar o UnityContainer.
Dessa forma o healthcheck vai resolver as dependências toda vez que der um CheckHealthAsync, tornando essa instância de MongoDbHealthCheck <transient>

Olhar: 
  * Classe registration
  * HealthCheck service método ResolveDependencies

2021-08-03 14:50 UTC, AndrePostiga commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/AspNetStandard.Diagnostics.HealthChecks.Wcf.csproj
> +    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
Este target deve apontar para 

<TargetFrameworks>netstandard2.0;net461;net472</TargetFrameworks>

2021-08-03 14:51 UTC, AndrePostiga commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/AspNetStandard.Diagnostics.HealthChecks.Wcf.csproj
> +  </ItemGroup>
Deve incluir esse item group pra passar na pipeline de CI CD

	<ItemGroup Condition="$(TargetFramework.StartsWith('net4')) AND '$(MSBuildRuntimeType)' == 'Core' AND '$(OS)' != 'Windows_NT'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0" PrivateAssets="All" />
	</ItemGroup>

2021-08-03 15:10 UTC, HelenMinin commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHealthCheckBuilder.cs
> +        public WcfHealthCheckBuilder AddCheck(string name, IHealthCheck healthCheck)
@vpecanha Sobre as classes que herdam IHealthCheck, elas já são publicas então não tem nenhum problema manter da maneira que está atualmente.
Sobre o segundo ponto, a ideia de criar métodos específicos é boa porém ela ficará para um outro momento, para ser feita também na implementação feita pelo Postiga. Por hora vamos manter igual para seguir o padrão que já existe no projeto.

2021-08-03 16:02 UTC, vpecanha commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHeathCheckRouteExtension.cs
> +        public static WcfHealthCheckBuilder AddWcfHealthCheck()
Se o padrão é Add então é melhor manter. Acho estranho pq na prática estamos criando.

2021-08-03 18:40 UTC, HelenMinin commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/WcfHeathCheckRouteExtension.cs
> +            RouteTable.Routes.Add(new ServiceRoute("health/", new WebServiceHostFactory(),
Feito.

2021-08-04 17:44 UTC, HelenMinin commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/AspNetStandard.Diagnostics.HealthChecks.Wcf.csproj
> +    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
Coloquei a tag igual o healthCheck já existente, atende o seu comentário ?

2021-08-10 20:58 UTC, ericksavassa approved these changes

2021-08-10 23:16 UTC, vpecanha commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/README.md
> +                .AddCheck("MyApi", new WcfHealthCheck()) // Faz o setup para o HealthCheck WCF
Poxa não entendi ainda, desculpas :(

2021-08-10 23:17 UTC, vpecanha reviewed
Não encontrei método para realizar ping.

Onde estaria?

2021-08-11 12:45 UTC, HelenMinin commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/AspNetStandard.Diagnostics.HealthChecks.Wcf.csproj
> +  </ItemGroup>
Feito!

2021-08-11 13:46 UTC, HelenMinin commented on src/AspNetStandard.Diagnostics.HealthChecksWcf/README.md
> +                .AddCheck("MyApi", new WcfHealthCheck()) // Faz o setup para o HealthCheck WCF
A diferença é apenas no retorno. Se eu colocar apenas o AddWcfHealthCheck() ele retorna apenas o OverAllStatus com o "Healthy" se ele colocar o .AddCheck("MyApi", new WcfHealthCheck()  o bloco HealthCheck vem preenchido com "mais detalhes"
na real eu vejo diferença quando apenas quando ele não está healthy, que trás mais detalhes do porq deu merda. quando ta ok parece redundante

2021-08-19 18:57 UTC, merged